name: Deploy Microservice

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r schedules_microservice/requirements.txt

    - name: Deploy to EC2
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'bash -s' < deploy_script.sh
      env:
        SSH_PRIVATE_KEY_PATH: ${{ secrets.SSH_PRIVATE_KEY_PATH }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
