# name: CI/CD Workflow
# trigger comment
# on:
#   push:
#     branches:
#       - main

# jobs:
#   create_infrastructure:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#       with:
#         node-version: 16

#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         terraform_version: 0.15.0

#     - name: Create infrastructure
#       run: |
#         cd terraform_create
#         terraform init
#         terraform apply -auto-approve
#       env:
#           TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
