name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_PRIVATE_IP: ${{ secrets.EC2_PRIVATE_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Debug
        run: |
          echo "Username: $EC2_USERNAME"
          echo "Private IP: $EC2_PRIVATE_IP"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_PRIVATE_IP 'bash -s' << 'EOF'
            cd schedules_microservice
            git pull origin main
            pip install -r requirements.txt
            python3 main.py
          EOF
