#comment for trigger 2
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_PUBLIC_IP '
            cd schedules_microservice
            git pull origin main
            pip install -r requirements.txt
            python3 main.py &
            app_pid=$!
            sleep 10
            response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
            echo "HTTP Status Code: $response_code"
            kill $app_pid
            if [ $response_code -eq 200 ]; then
              echo "HTTP Status Code is 200. Marking the job as successful."
              exit 0
            else
              echo "Error: HTTP Status Code is not 200. Marking the job as failed."
              exit 1
            fi
            '